[versions]
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.09.00"
material3-adaptive = "1.2.0-beta02"
material3-adaptive-layout = "1.2.0-beta02"
material3-adaptive-navigation = "1.2.0-beta02"
koin="4.1.1"
coil-version="3.3.0"
composeNavigation="2.9.5"
serializationJson="1.9.0"
runtime = "1.9.3"
roomCompiler = "2.8.2"
roomKtx = "2.8.2"
roomRuntime = "2.8.2"
ksp = "2.2.0-Beta2-2.0.1"
navigationCompose = "2.9.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3-adaptive" }
androidx-material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3-adaptive-layout" }
androidx-material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3-adaptive-navigation" }
androidx-koin-android-compose= { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
androidx-koin-android-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koin" }
androidx-coil-compose={ group = "io.coil-kt.coil3", name = "coil-compose", version.ref= "coil-version" }
androidx-coil-network-okhttp={ group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref= "coil-version" }
navigaton-compose={module="androidx.navigation:navigation-compose",version.ref="composeNavigation"}
kotlinx-serialization-json={module="org.jetbrains.kotlinx:kotlinx-serialization-json",version.ref="serializationJson"}
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization={id="org.jetbrains.kotlin.plugin.serialization",version.ref="kotlin"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
safeArgs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationCompose" }
